board/urls.py
from django.urls import path
from .views import *

app_name = 'board'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('<int:pk>', PostDetailView.as_view(), name='post_detail'),

    path('add/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('categories/<str:cat_disp> <cat_key>', CategoryDetailView.as_view(), name='category_detail'),
    path('author/<int:author_pk>', AuthorPostsListView.as_view(), name='author_posts'),

    path('show_replies/', ReplyListView.as_view(), name='show_replies'),

    path('accept_reply/<int:pk>', accept_reply, name='accept_reply'),
    path('delete_reply/<int:pk>', delete_reply, name='delete_reply'),
]

mmorpg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls', namespace='board')),
    path('accounts/', include('allauth.urls')),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.core.cache import cache


class Post(models.Model):
    TANK = 'TK'
    HEALER = 'HL'
    DAMAGE_DEALER = 'DD'
    TRADER = 'TD'
    GUILD_MASTER = 'GM'
    QUEST_GIVER = 'QG'
    BLACKSMITH = 'BS'
    TANNER = 'TN'
    POTION_MASTER = 'PM'
    SPELL_MASTER = 'SM'

    CATEGORIES = [
        (TANK, 'Танки'),
        (HEALER, 'Хилы'),
        (DAMAGE_DEALER, 'ДД'),
        (TRADER, 'Торговцы'),
        (GUILD_MASTER, 'Гилдмастеры'),
        (QUEST_GIVER, 'Квестгиверы'),
        (BLACKSMITH, 'Кузнецы'),
        (TANNER, 'Кожевники'),
        (POTION_MASTER, 'Зельевары'),
        (SPELL_MASTER, 'Мастера заклинаний'),
    ]

    title = models.CharField(max_length=128, verbose_name='Заголовок')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    category = models.CharField(max_length=2, choices=CATEGORIES, default=TANK, verbose_name='Категория')
    content = RichTextField(verbose_name='Содержание объявления')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    dateUpdate = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/{self.pk}'

    # D7.4.Кэширование на низком уровне (смотри еще view PostDetailView метод get_object)
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его


class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Как Вам статья?')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Объявление')
    dateCreation = models.DateTimeField(auto_now_add=True)
    accepted = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.post} ==> {self.author}: {self.text}'

board/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post, Reply


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'category',
            'title',
            'content',
        ]
        widgets = {
            'content': forms.CharField(widget=CKEditorWidget()),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['text', ]
        widgets = {
          'text': forms.Textarea(attrs={'rows': 4, 'cols': 70}),
        }

board/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.utils import timezone

from django.shortcuts import redirect
from django.contrib.auth.models import User

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import ReplyForm, PostForm
from .models import Post, Reply
from .filters import ReplyFilter
from .tasks import notify_accept_reply, notify_new_reply


class PostListView(ListView):
    model = Post
    template_name = 'board/posts.html'
    context_object_name = 'posts'
    ordering = ['-dateCreation']
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        context['posts_count'] = Post.objects.all().count()  # добавим переменную кол-во постов
        return context


class PostDetailView(DetailView, CreateView):
    model = Post
    form_class = ReplyForm
    template_name = 'board/post_detail.html'
    context_object_name = 'post'

    def form_valid(self, form):
        reply = form.save(commit=False)
        reply.author = User.objects.get(id=self.request.user.id)
        reply.post = Post.objects.get(id=self.kwargs.get('pk'))
        reply.save()
        notify_new_reply(reply.id)
        return redirect('board:posts')

    # D7.4 Кэширование на низком уровне (смотри еще модель Post метод save)
    def get_object(self, *args, **kwargs):  # переопределяем метод получения объекта, как ни странно
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)  # кэш очень похож на словарь, и
        # метод get действует также. Он забирает значение по ключу, если его нет, то забирает None.

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj)
        return obj


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'board/post_create.html'
    form_class = PostForm

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = User.objects.get(id=self.request.user.id)
        post.save()
        return redirect('board:posts')


class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'board/post_update.html'
    form_class = PostForm

    def get_object(self, **kwargs):
        id_pk = self.kwargs.get('pk')
        return Post.objects.get(pk=id_pk)

    def dispatch(self, request, *args, **kwargs):
        if self.request.user == Post.objects.get(pk=self.kwargs.get('pk')).author:
            return super().dispatch(request, *args, **kwargs)
        else:
            return HttpResponse('<h3>ACCESS DENIED!</h3>Изменять или удалять можно только свои объявления!')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'board/post_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('board:posts')
    permission_required = ('board.delete_post',)

    def dispatch(self, request, *args, **kwargs):
        if self.request.user == Post.objects.get(pk=self.kwargs.get('pk')).author:
            return super().dispatch(request, *args, **kwargs)
        else:
            return HttpResponse('<h3>ACCESS DENIED!</h3>Изменять или удалять можно только свои объявления!')


class CategoryDetailView(ListView):
    model = Post
    template_name = 'board/posts.html'
    context_object_name = 'posts'
    ordering = ['-id']
    paginate_by = 3

    def get_queryset(self):
        cat_key = self.kwargs['cat_key']
        queryset = Post.objects.filter(category=cat_key)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat_key = self.kwargs['cat_key']
        cat_display = self.kwargs['cat_disp']
        context['category'] = cat_display
        context['posts_count'] = Post.objects.filter(category=cat_key).count()  # добавим переменную кол-во постов
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        return context


class AuthorPostsListView(ListView):
    model = Post
    template_name = 'board/posts.html'
    context_object_name = 'posts'
    ordering = ['-id']
    paginate_by = 3

    def get_queryset(self):
        author_pk = self.kwargs['author_pk']
        queryset = Post.objects.filter(author_id=author_pk)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author_pk = self.kwargs['author_pk']
        context['author'] = User.objects.get(pk=author_pk)
        context['posts_count'] = Post.objects.filter(author_id=author_pk).count()  # добавим переменную кол-во постов
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        return context


class ReplyListView(ListView):
    model = Reply
    template_name = 'board/show_replies.html'
    context_object_name = 'replies'

    def get_queryset(self):
        return super().get_queryset().filter(post_id__author_id=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = ReplyFilter(self.request.GET, queryset=self.get_queryset())
        return context


def accept_reply(*args, **kwargs):
    reply = Reply.objects.get(id=kwargs.get('pk'))
    reply.accepted = True
    reply.save()
    notify_accept_reply(reply.id)
    return redirect('board:show_replies')


def delete_reply(*args, **kwargs):
    reply = Reply.objects.get(id=kwargs.get('pk'))
    reply.delete()
    return redirect('board:show_replies')

board/templates/board/categories.html
{% extends 'layout/default.html' %}

{% load custom_filters %}

{% block title %}
    Категории новостей
{% endblock title %}

{% block content %}
    <h1 align="center">Категории новостей и статей:</h1>

    <div class="d-flex justify-content-center flex-wrap">

        {% for category in categories %}

            <div class="w-30 p-2 col-sm-4" style="width: 300px">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'news:category_detail' category.pk %}" class="btn btn-primary btn-lg">{{ category.name }}</a>
                        {% if user in category.subscribers.filter %}
                            <button type="button" class="btn btn-info btn-sm" disabled>Вы подписаны</button>
                        {% endif %}

                        <br><br>
                        <p class="card-text"> Статей: {{ category.post_set.count }}</p>
                        <p class="card-text"> Подписчиков: {{ category.subscribers.count }}</p>
                        <a href="{% url 'news:category_detail' category.pk %}" class="btn btn-info">Статьи</a>

                        {% if user not in category.subscribers.filter %}
                            <a href="{% url 'news:subscribe' category.pk %}" class="btn btn-primary btn-sm">Подписаться</a>
                        {% else %}
                            <a href="{% url 'news:unsubscribe' category.pk %}" class="btn btn-secondary btn-sm">Отписаться</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        {% endfor %}

    </div>

{% endblock content %}

board/templates/board/category_detail.html
{% extends 'layout/default.html' %}

{#{% load custom_filters %}#}

{% block title %}
    Новость: {{ post.title }}
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h3>{{ post.title }}</h3>
            <div>
                Автор: <span class="badge bg-info">{{ post.author }}</span>
                Категория: <span class="badge bg-info">{{ post.get_category_display }}</span>
                {#        Категории: <span class="badge bg-info">{{ post.postCategory.name }}</span>#}
                {#        Категории: <span class="badge bg-info">{{ post.postCategory.all }}</span>#}
{#                Категории:#}
{#                <span class="badge bg-info">#}
{#                    {% for k in  post.postCategory.all %}#}
{#                        {{ k }},#}
{#                    {% endfor %}#}
{#                </span>#}
            </div>
        </div>
        <div class="card-body">{{ post.text }}</div>
    </div>
    <a href="{% url 'board:posts' %}" class="btn btn-primary my-3">В начало</a>

{% endblock content %}

board/templates/board/postSearch.html
<!--  наследуемся от шаблона base.html -->
{% extends 'layout/default.html' %}

<!-- не забываем заранее загружать наши фильтры! -->
{% load custom_filters %}

<!-- Название у нас будет Новости, статьи -->
{% block title %}
    Поиск новости, статьи
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
    <h1 align="center" >Поиск новости или статьи:</h1>
    <h5 align="right">{{ time_now| date:'d-M-Y H:i' }}</h5>
    <hr>
    <h5 align="center"><i><u> Найдено новостей и статей: {{ filter.qs|length }} из {{ posts_count }}</u></i></h5>
    <br>

    {% if posts %}

        <!-- Перед таблицей добавим форму для поиска -->
        <form method="GET">
            {{ filter.form }}
            <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
            <input class="btn btn-primary" type="submit" value="Найти">
        </form>

        <table class="table">
            <tr>
                <th scope="col"> Название</th>
                <th scope="col"><p align="justify"> Дата публикации</p></th>
                <th scope="col">Содержимое</th>
                <th scope="col">Действия</th>

            </tr>
            {#            {% for post in filter.qs %}#}
            {% for post in posts %}
                <tr class="{% cycle 'blue_tr' 'white_tr' %}">
                    <td>
                        <a href="{% url 'news:post_detail' post.pk %}">
                            {{ post.title|truncatewords:8|truncatechars:50|Censor }}
                        </a>
                    </td>
                    <td>{{ post.dateCreation| date:'d-M-Y H:i' }}</td>
                    <td>{{ post.text|truncatechars:50|Censor }}</td>
                    <td>
                        <a href="{% url 'news:post_update' post.pk %}">Редактирование</a>
                        <a href="{% url 'news:post_delete' post.pk %}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}

        </table>

        {% include 'news/parts/paginator.html' %}

    {% else %}
        <h2 align="center">Новостей и статей нет!</h2>

    {% endif %}

{% endblock content %}

board/templates/board/post_create.html
{% extends 'layout/default.html' %}


{% block title %}
Создание статьи
{% endblock title %}

{% block content %}

<h3>Добавление объявления</h3>

<form method="POST">
 {% csrf_token %}
 {{ form.media }}
 {{ form.as_p }}
   <input class="btn btn-success my-button" type="submit" value="Добавить">
</form>

{% endblock content %}

board/templates/board/post_delete.html
{% extends 'layout/default.html' %}

{% block title %}
    Удаление статьи
{% endblock title %}

{% block content %}
    <h3>Вы действительно хотите удалить статью?</h3>
    <div class="card">
        <div class="card-header">
            <h3>{{ post.title }} </h3>
            <div>
{#                Автор: <span class="badge bg-info">{{ post.author }}</span>#}
                Автор: <span class="button btn-sm btn-info">{{ post.author }}</span>
{#                Категория: <span class="badge bg-info">{{ post.get_category_display }}</span>#}
                &nbsp;&nbsp; Категория: <span class="button btn-sm btn-info">{{ post.get_category_display }}</span>
            </div>
        </div>
        <div class="card-body">{{ post.text }}</div>
    </div>
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-success my-button" type="submit" value="Подтвердить">
    </form>

{% endblock content %}

board/templates/board/post_detail.html
{% extends 'layout/default.html' %}

<!-- не забываем заранее загружать наши фильтры! -->
{#{% load custom_filters %}#}

<!-- Название у нас будет "Новость или статья - Заголовок..." -->
{% block title %}
    {{ post.get_categoryType_display }}: {{ post.title|truncatechars:10  }}
{% endblock title %}

<!-- В контенте на странице мы выводим саму Новость или статью,
 первичный ключ которого был передан в адрес -->
{% block content %}
    <h1 align="center">{{ post.title }}</h1>

    {#<!--  ===== Card Header =====-->#}
    {% include './parts/card_header.html' %}
    {#<!--  ===== End Card Header =====-->#}

    <p>{{ post.content|safe }}</p>

{#    ===========================#}
    {% if user == post.author %}
        <a href="{% url 'board:post_update' post.id %}" class="btn btn-primary">Редактировать</a>
        <a href="{% url 'board:post_delete' post.id %}" class="btn btn-primary">Удалить</a>
    {% elif user.is_authenticated %}
        <form method="POST">
            {% csrf_token %}
            <div class="card card-footer align-content-center">
                {#                {{ form.as_p }}#}
                {{ form.as_table }}
                <input type="submit" value="Отправить отклик" class="btn btn-primary">
            </div>
        </form>
    {% endif %}

    <hr>
    <a href="{% url 'board:posts' %}" class="btn btn-primary">Вернуться на главную страницу</a>

{#    ===========================#}

{% endblock content %}

board/templates/board/post_detail_1_old.html
{% extends 'layout/default.html' %}

{#{% load custom_filters %}#}

{% block title %}
    Новость: {{ post.title }}
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h3>{{ post.title }}</h3>
            <div>
                Автор: <span class="badge bg-info">{{ post.author }}</span>
                Категория: <span class="badge bg-info">{{ post.get_category_display }}</span>
                {#        Категории: <span class="badge bg-info">{{ post.postCategory.name }}</span>#}
                {#        Категории: <span class="badge bg-info">{{ post.postCategory.all }}</span>#}
{#                Категории:#}
{#                <span class="badge bg-info">#}
{#                    {% for k in  post.postCategory.all %}#}
{#                        {{ k }},#}
{#                    {% endfor %}#}
{#                </span>#}
            </div>
        </div>
        <div class="card-body">{{ post.text }}</div>
    </div>
    <a href="{% url 'board:posts' %}" class="btn btn-primary my-3">В начало</a>

{% endblock content %}

board/templates/board/post_update.html
{% extends 'layout/default.html' %}


{% block title %}
Редактирование объявления
{% endblock title %}

{% block content %}
<h3>Редактирование объявления</h3>

<form method="POST">
 {% csrf_token %}
 {{ form.media }}
 {{ form.as_p }}
   <input class="btn btn-success my-button" type="submit" value="Изменить">
</form>

<hr>
<a href="{% url 'board:posts' %}" class="btn btn-primary">Вернуться на главную страницу</a>

{% endblock content %}

board/templates/board/posts.html
{% extends 'layout/default.html' %}

{% block title %}
    Объявления
{% endblock title %}

{% block content %}
    {% if category %}
        <h5 align="center" ><b>Объявления в категории `{{ category }}`:</b></h5>
        <p align="center"><i><u> Всего объявлений: {{ posts_count }}
            (на странице: {{ posts|length }})</u></i>
        </p>
    {% elif author %}
        <h5 align="center" ><b>Объявления автора: `{{ author }}`:</b></h5>
        <p align="center"><i><u> Всего объявлений: {{ posts_count }}
            (на странице: {{ posts|length }})</u></i>
        </p>
    {% else %}
        <p align="center"><i><u> Всего объявлений: {{ posts_count }}
            (на странице: {{ posts|length }})</u></i>
        </p>
        <hr>
    {% endif %}

    {% if posts %}
        <table class="table">
            {% for post in posts %}
                <div class="p-3 w-auto blue_tr %}">
                    <div class="card">
                        {#<!--  ===== Card Header =====-->#}
                        {% include './parts/card_header.html' %}
                        {#<!--  ===== End Card Header =====-->#}
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url 'board:post_detail' post.pk %}">
                                    {{ post.title|truncatewords:10|truncatechars:70 }}
                                </a>
                            </h5>
                            <p class="card-text">

                                {{ post.content|safe |truncatewords:40}}
                            </p>
                            <a href="{% url 'board:post_detail' post.pk %}" class="btn btn-outline-primary btn-sm">Перейти ...</a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        </table>

        {% include 'board/parts/paginator.html' %}


    {% else %}
        <h3 align="center">Объявлений нет!</h3>

    {% endif %}

{% endblock content %}


{#=======================================#}
{#=======================================#}
{#=======================================#}
{#=======================================#}

board/templates/board/show_replies.html
{% extends 'layout/default.html' %}

{% block title %}
    Отклики
{% endblock title %}

{% block content %}

    <form method="GET">
        {{ filter.form }}
        <input class="btn btn-primary" type="submit" value="Найти">
    </form>

    {% for r in filter.qs %}

        {% if r.post.author == user %}
            <div>
                <hr>
                {{ r }}
                <br>
                {% if not r.accepted %}
                    <span class="text-danger">Отклик не обработан!</span>
                    <a href="{% url 'board:accept_reply' r.id %}" class="btn btn-outline-info btn-sm">
                        Принять
                    </a>
                {% else %}
                    <span class="text-success">Принято!</span>
                {% endif %}
                <a href="{% url 'board:delete_reply' r.id %}" class="btn btn-outline-danger btn-sm">
                    Удалить
                </a>
                <hr>
            </div>
        {% endif %}

    {% endfor %}

{% endblock content %}