board/urls.py
from django.urls import path
from .views import *

app_name = 'board'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('<int:pk>', PostDetailView.as_view(), name='post_detail'),

    path('add/', PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('categories/<str:cat_disp> <cat_key>', CategoryDetailView.as_view(), name='category_detail'),
    path('author/<int:author_pk>', AuthorPostsListView.as_view(), name='author_posts'),

    path('show_replies/', ReplyListView.as_view(), name='show_replies'),

    path('accept_reply/<int:pk>', accept_reply, name='accept_reply'),
    path('delete_reply/<int:pk>', delete_reply, name='delete_reply'),
]

mmorpg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls', namespace='board')),
    path('accounts/', include('allauth.urls')),
]

templates/layout/parts/footer.html
<footer class="footer mt-auto py-2 sticky-bottom fixed-bottom" style="background-color: #EBEBFF;">
    <div class="container">
        <!--  <div class="container-fluid text-center text-md-left">-->
        <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>

templates/layout/parts/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #001D24;">
    <a class="navbar-brand" target="_blank"  href="https://www.mmorpg.com/">
        <img src="{% static 'board/img/logo_mmorpg.svg' %}" alt="Logo" width="120" height="30" class="d-inline-block align-text-top">
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Доска объявлений <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:post_create' %}">Создать объявление</a>
                </li>
            {% endif %}
        </ul>

        <div class="text-end">
            {% if user.is_authenticated %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li>
                        <a href="{% url 'account_logout' %}" class="nav-link px-2 text">
                            <button type="button" class="btn btn-outline-info btn-sm">
                                Выйти
                            </button>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" type="button" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <button type="button" class="btn btn-outline-info btn-sm" disabled>
                                {{ user.username }}
                            </button>
                        </a>

                        <div class="dropdown-menu align-baseline" aria-labelledby="navbarDropdown">
                            <div class="d-grid gap-2">

                                <a class="btn btn-outline-info btn-md" href="{% url 'board:author_posts' user.pk %}">
                                    &nbsp;&nbsp;Мои объявления
                                </a>
                                <a class="btn btn-outline-info btn-md" href="{% url 'board:show_replies'%}">
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    Отклики &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </a>

                                <div class="dropdown-divider "></div>
                                <a class="btn btn-outline-info btn-md" href="{% url 'account_logout' %}">
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    Выйти  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                </a>
                            </div>
                        </div>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;
                    <li>
                        <a href="" class="nav-link px-2 text">
                            <button class="btn btn-outline-warning btn-sm" disabled>
                                {{ time_now| date:'d-M-Y H:i' }}
                            </button>
                        </a>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                </ul>

            {% else %}
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li>
                        <a href="{% url 'account_login' %}" class="nav-link px-2">
                            <button type="button" class="btn btn-outline-primary btn-sm me-2">
                                Войти
                            </button>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'account_signup' %}" class="nav-link px-2">
                            <button type="button" class="btn btn-outline-primary btn-sm me-2">
                                Регистрация
                            </button>
                        </a>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <li>
                        <a href="" class="nav-link px-2 text">
                            <button class="btn btn-outline-warning btn-sm" disabled>
                                {{ time_now| date:'d-M-Y H:i' }}
                            </button>
                        </a>
                    </li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                </ul>
            {% endif %}
        </div>
    </div>
</nav>